# Generated by Django 4.2.4 on 2023-09-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_favourite_recipe_alter_favourite_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipesingredient',
            old_name='count',
            new_name='amount',
        ),
    ]
